services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:example@db:5432/postgres
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5432"