import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="site-header">
        <div className="site-header__wrapper">
          <span>Img</span>
          <span>Logo</span>
        </div>

        <section className="site-header__menu">
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/favorites">Favorites</Link>
        </section>

        <section className="site-header__login">
          <span>Button</span>
        </section>
      </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <footer className="site-footer">

      </footer>
    </html>
  );
}
